#include <stdio.h>
#include "ft_printf.h"

int	main()
{
	int	i = 123456;
	int	x = 113;
	char	c = 'c';
	unsigned int	u = 123;
	char	*s = "salutcava";
	void	*p = 0x12345;

	printf("\nTESTING INTEGER\n");
	ft_printf("%i\n", i);
	printf("\nTESTING CHARACTER\n");
	ft_printf("test%c", c);
	printf("\nTESTING STRING\n");
	ft_printf("test%s", s);
	printf("\nTESTING UNSIGNED\n");
	ft_printf("test%u", u);
	printf("\nTESTING DECIMAL\n");
	ft_printf("test%d", i);
	printf("\nTESTING HEX MIN\n");
	ft_printf("test%x", x);
	printf("\nTESTING HEX MAJ\n");
	ft_printf("test%X", x);
	printf("TESTINT POINTER\n");
//	ft_printf("%p\n", p);
//	printf("MODULOS\n");
//	ft_printf("%%\n");
	printf("\nTESTING COMBOS\n");
        printf("\nTESTING string with flags\n");
	ft_printf("s with space     :%s", s);
	printf("\n");
	ft_printf("s with minus     :%s", s);
	printf("\n");
	ft_printf("s with sharp     :%s", s);
	printf("\n");
	ft_printf("s with precision :%s", s);
	printf("\n");
	ft_printf("s with plus      :%s", s);
	printf("\n");
	ft_printf("s with zeros     :%s", s);
	printf("\n");
	printf("\nTESTING char with flags\n");
	ft_printf("c with space     :%c", c);
	printf("\n");
	ft_printf("c with minus     :%c", c);
	printf("\n");
	ft_printf("c with sharp     :%c", c);
	printf("\n");
	ft_printf("c with precision :%c", c);
	printf("\n");
	ft_printf("c with plus      :%c", c);
	printf("\n");
	ft_printf("c with zerso     :%c", c);
	printf("\nTESTING int with flags\n");
	ft_printf("i with space     :%i", i);
	printf("\n");
	ft_printf("i with minus     :%i", i);
	printf("\n");
	ft_printf("i with sharp     :%i", i);
	printf("\n");
	ft_printf("i with precision :%i", i);
	printf("\n");
	ft_printf("i with plus      :%i", i);
	printf("\n");
	ft_printf("i with zeros     :%i", i);
	printf("\nTESTING DECIMAL\n");
	ft_printf("d with space     :%d", i);
        printf("\n");
	ft_printf("d with minus     :%d", i);
        printf("\n");
	ft_printf("d with sharp     :%d", i);
        printf("\n");
	ft_printf("d with precision :%d", i);
        printf("\n");
	ft_printf("d with plus      :%d", i);
        printf("\n");
	ft_printf("d with zeros     :%d", i);
	printf("\nTESTING uns with flags\n");
	ft_printf("u with space     :%u", u);
	printf("\n");
	ft_printf("u with minus     :%u", u);
	printf("\n");
	ft_printf("u with sharp     :%u", u);
	printf("\n");
	ft_printf("u with precision :%u", u);
	printf("\n");
	ft_printf("u with plus      :%u", u);
	printf("\n");
	ft_printf("u with zeros     :%u", u);
	printf("\nTESTING hex with flags\n");
	ft_printf("x with space     :%x", x);
	printf("\n");
	ft_printf("x with minus     :%x", x);
	printf("\n");
	ft_printf("x with sharp     :%x", x);
	printf("\n");
	ft_printf("x with precision :%x", x);
	printf("\n");
	ft_printf("x with plus      :%x", x);
	printf("\n");
	ft_printf("x with zeros     :%x", x);
	printf("\nTESTING ptr with flags\n");
	ft_printf("p with space     :%p", p);
	printf("\n");
	ft_printf("p with minus     :%p", p);
	printf("\n");
	ft_printf("p with sharp     :%p", p);
	printf("\n");
	ft_printf("p with precision :%p", p);
	printf("\n");
	ft_printf("p with plus      :%p", p);
	printf("\n");
	ft_printf("p with zeros     :%p", p);
	printf("\nTESTING HEX with flags\n");
	ft_printf("X with space     :%X", x);
	printf("\n");
	ft_printf("X with minus     :%X", x);
	printf("\n");
	ft_printf("X with sharp     :%X", x);
	printf("\n");
	ft_printf("X with precision :%X", x);
	printf("\n");
	ft_printf("X with plus      :%X", x);
	printf("\n");
	ft_printf("X with zeros     :%X", x);
	printf("\nTESTING MOD with flags\n");
	ft_printf("%%");
	return (0);
}
